[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mutation_motif"
authors = [{ name = "Gavin Huttley", email = "Gavin.Huttley@anu.edu.au" }]
keywords = [
    "biology",
    "genomics",
    "statistics",
    "genetics",
    "evolution",
    "bioinformatics",
    "mutation",
]
readme = "README.md"
license = { file = "license.txt" }
requires-python = ">=3.11,<3.15"
dependencies = [
    "click",
    "cogent3>=2026.5.19a0",
    "kaleido",
    "numpy",
    "scipy",
    "scitrack",
    "pandas",
    "plotly",
    "scipy",
    "statsmodels",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
description = "Analyses of point mutation counts data using log-linear models"
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/HuttleyLab/MutationMotif"
"Bug Tracker" = "https://github.com/HuttleyLab/MutationMotif/issues"
"Source Code" = "https://github.com/HuttleyLab/MutationMotif"

[project.scripts]
mm = "mutation_motif.cli:main"

[dependency-groups]
test = ["pytest", "pytest-cov", "nox"]
dev = ["click", "cog", "pytest", "pytest-cov", "nox", "ruff"]

[tool.pytest.ini_options]
addopts = ["--strict-config", "-ra"]
testpaths = "tests"
markers = ["draws: tests that draw images (deselect with '-m \"not draws\"')"]

[tool.hatch.version]
path = "src/mutation_motif/__init__.py"

[tool.uv]
reinstall-package = ["mutation_motif"]
# Minimize the risk of supply chain attacks
exclude-newer = "7 days"

[tool.uv.pip.exclude-newer-package]
# but we allow cogent3 packages to be more recent
scinexus = false
cogent3 = false
