name: "Test against Cogent3 develop branch"

on:
    schedule:
      - cron: '0 21 * * *' # 7am AEST
    workflow_dispatch:  # support for manual triggering

jobs:
  cogent3-dev:
    name: "cogent3-dev"
    runs-on: ubuntu-latest
    if: github.repository == 'HuttleyLab/MutationMotif'

    steps:
      - uses: "actions/checkout@v6.0.2"
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install project + test group
        run: |
          uv venv
          uv pip install -e . --group test

      - name: Override cogent3 with dev branch
        run: uv pip install --refresh "cogent3 @ git+https://github.com/cogent3/cogent3.git@develop"

      - name: Run tests
        run: uv run pytest tests
