name: Lint code using ruff

on:
  push:
    branches-ignore:
      - master

jobs:
  linters:
    runs-on: ubuntu-latest
    if: github.repository == 'HuttleyLab/MutationMotif'
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          python-version: "3.14"

      - name: Format code using ruff
        run: uv run --group dev nox -s fmt

      - name: Commit changes
        uses: EndBug/add-and-commit@v10
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "STY: pre-commit linting with ruff"
          add: "."
